import Head from "next/head";
import { BsFillMoonStarsFill, BsSunFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillMail } from "react-icons/ai";
import Image from "next/image";
import headshot from "../public/headshot.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Xueyi Yao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white dark:bg-gray-900">
        <nav className=" p-10 flex justify-between">
          <h1 className=" text-xl font-burtons dark:text-gray-200">
            xueyi yao
          </h1>
          <ul className=" flex items-center">
            <li>
              {darkMode ? (
                <BsSunFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-gray-200"
                />
              ) : (
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              )}
            </li>
            <li>
              <a
                className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                target="_blank"
                rel="noopener noreferrer"
                href="https://s3.amazonaws.com/attachments.angel.co/7651896-8e1dab2994004dc3efd1ebaf4bfe80bc.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJS6W3HGZGRJIRBTA%2F20221201%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221201T024120Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=ec8405eb3cd687f3a5c9595079b5cfe14daaea209b566a4548862887b004914e"
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        <section className=" px-10 min-h-screen">
          <div className=" relative bg-gradient-to-b from-teal-500 rounded-full w-72 h-72 mt-12 mx-auto overflow-hidden">
            <Image src={headshot} />
          </div>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 dark:text-teal-400 font-medium">
              Xueyi Yao
            </h2>
            <h3 className=" text-2xl py-2 dark:text-gray-200">
              Software Engineer
            </h3>
            <p className="  text-md py-5 leading-8 text-gray-800 dark:text-gray-400">
              I'm a software engineer and tech enthusiast from San Francisco. I
              enjoy building things and am always excited to learn something
              new! Welcome to my site!
            </p>
            <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://github.com/xueyiyao"
              >
                <AiFillGithub />
              </a>
              <a
                target="_blank"
                rel="noopener noreferrer"
                href="https://www.linkedin.com/in/xueyi-yao/"
              >
                <AiFillLinkedin />
              </a>
              <a href="mailto: allenxueyiyao@gmail.com">
                <AiFillMail className=" " />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
